name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'poetry'
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
          poetry install --all-extras
      - name: Black
        run: |
          poetry run black . --check --diff --color --verbose
      - name: Flake8
        run: |
          poetry run flake8
      - name: isort
        run: |
          poetry run isort --check --diff .
      - name: mypy
        run: |
          poetry run mypy --install-types --non-interactive . --strict
